feat: implement hero section of Get Involved page
aseanbya/ABYAWebsite pull request #30
Opened 2023-08-13 04:42 UTC by zsh-eng

Resolves #25

I did not hardcode the colour values for the button. Are we going to include the brand colours into the Tailwind CSS config?

2023-08-14 08:20 UTC, javianng requested changes

2023-08-14 08:20 UTC, javianng commented on src/pages/getInvolved/index.tsx
> +        <div className="card w-full border border-blue-500 bg-base-100 px-4 pt-6 shadow-xl lg:w-[428px] lg:px-7 lg:pt-8">
can use border-brandBlue instead

2023-08-14 08:20 UTC, javianng commented on src/pages/getInvolved/index.tsx
> +                    <h1 className="text-5xl font-bold uppercase tracking-wide">
text-black

2023-08-14 08:20 UTC, javianng commented on src/pages/getInvolved/index.tsx
> +                    <Button href={href}>Learn More</Button>
I think the button colors are not accurate

2023-08-14 08:20 UTC, javianng commented on src/pages/getInvolved/index.tsx
> +            <section className="my-4 flex w-screen flex-col justify-center gap-5 px-2 lg:flex-row lg:px-10">
i think the responsiveness of the card is causing some issues at certain screen width sizes. 

perhaps you can consider 
- not hardcoding the width of the card so that the card can resize and not extend beyond the width of the screen
- overflow:scroll

2023-08-20 03:16 UTC, zsh-eng commented
@javianng I've resolved merge conflicts and made the changes you suggested. Do let me know if there are any other changes to be made!

2023-08-21 16:06 UTC, javianng approved these changes

2023-08-21 16:06 UTC, merged